Food-Delivery-Website-master/FoodAppUILayer/Controllers/RatingController.cs
using FoodAppDALLayer.Interface;
using FoodAppDALLayer.Models;
using FoodAppDALLayer.Repository;
using FoodAppUILayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FoodAppUILayer.Controllers
{
    public class RatingController : Controller
    {
        private IRatingRepository ratingRepository;


        public RatingController(IRatingRepository ratingRepository)
        {
            this.ratingRepository = ratingRepository;

        }

        public ActionResult AddRatings(int id)
        {
            ViewBag.orderid = id;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRatings(Rating rating)
        {
            int userid = (int)Session["UserId"];
            Rating rat = new Rating();
            {
                rat.RatingCount = rating.RatingCount;
                rat.RatingId = rating.RatingId;
                rat.Comments = rating.Comments;
                rat.UserId = userid;
            };
            ratingRepository.InsertRating(rating);
            ratingRepository.Save();
            return RedirectToAction("ThankYou");
        }

        public ActionResult ThankYou()
        {
            return View();
        }

    }
}

Food-Delivery-Website-master/FoodAppUILayer/Controllers/UserController.cs
using FoodAppDALLayer.Interface;
using FoodAppDALLayer.Models;
using FoodAppDALLayer.Repository;
using FoodAppUILayer.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using FoodAppDALLayer.ApplicationDbContext;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Net;
using System.Reflection;
using FoodAppDALLayer.Migrations;

namespace FoodAppUILayer.Controllers
{
    [Authorize(Roles = "User")]
    public class UserController : Controller
    {
        public UserController()
        {

        }
  
        private readonly IFoodItemRepository foodItemRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly IRestaurantRepository restaurantRepository;
        private readonly ICartRepository cartRepository;
        private readonly IUserRepository userRepository;
        private readonly IAddressRepository addressRepository;
        private readonly IOrderItemRepository orderItemRepository;

        private readonly IOrderRepository orderRepository;

        public UserController(IRestaurantRepository restaurantRepository, ICategoryRepository categoryRepository, IFoodItemRepository foodItemRepository, ICartRepository cartRepository, IUserRepository userRepository, IAddressRepository addressRepository, IOrderRepository orderRepository, IOrderItemRepository orderItemRepository)
        {
            this.foodItemRepository = foodItemRepository ?? throw new ArgumentNullException(nameof(foodItemRepository));
            this.categoryRepository = categoryRepository ?? throw new ArgumentNullException(nameof(categoryRepository));
            this.restaurantRepository = restaurantRepository ?? throw new ArgumentNullException(nameof(restaurantRepository));
            this.cartRepository = cartRepository ?? throw new ArgumentNullException(nameof(cartRepository));
            this.userRepository = userRepository ?? throw new ArgumentNullException(nameof(userRepository));
            this.addressRepository = addressRepository ?? throw new ArgumentNullException(nameof(addressRepository));
            this.orderRepository = orderRepository ?? throw new ArgumentNullException(nameof(userRepository));
            this.orderItemRepository = orderItemRepository ?? throw new ArgumentNullException(nameof(userRepository));
        }

        public ActionResult AllRestaurant()
        {

            var rest = restaurantRepository.GetAllRestaurants();
            var top5orders = orderRepository.GetTop5OrdersByFoodId();
            ViewBag.Top5Orders = top5orders;

            var restaurantModel = rest.Select(MapToViewModel).ToList();

            return View(restaurantModel);
        }
        //MapToViewModel for Restaurant
        private Restaurant MapToViewModel(Restaurant rest)
        {
            return new Restaurant
            {
            RestId = rest.RestId,
            Name = rest.Name,
            Address = rest.Address,
            City = rest.City,
            Email = rest.Email,
            Mobile = rest.Mobile,
            Latitude = rest.Latitude,
            Longitude = rest.Longitude, 
            Image = rest.Image,

            };
        }

        public ActionResult AllFoodItems(int id)
        {
            var foodItem = foodItemRepository.GetFoodItemByRestId(id);
          
            var foodItemModel = foodItem.Select(MapToViewModel).ToList();

            return View(foodItemModel);

        }
       


        private FoodItem MapToViewModel(FoodItem foodItem)
        {
            return new FoodItem
            {
                FoodId = foodItem.FoodId,
                Availability = foodItem.Availability,
                Name = foodItem.Name,
                Image = foodItem.Image,
                Category = foodItem.Category,
                Description = foodItem.Description,
                Restaurant = foodItem.Restaurant,
                RestId = foodItem.RestId,
                Price = foodItem.Price,
            };
        }

        //cart
        [HttpPost]
        public ActionResult AddToCart(int foodItemId)
        {
            var userId = Session["UserId"] as int?;
            if (userId == null)
            {
                ModelState.AddModelError("errorMessage", "User session not found. Please log in.");
                return RedirectToAction("UserLogin", "Account");
            }
            int temp = Convert.ToInt32(userId);
            var existingCartItems = cartRepository.GetCartItemsByUserId(temp);
            var foodItems = foodItemRepository.GetFoodItemById(foodItemId);
            if (existingCartItems.Any())
            {
                bool sameRestaurant = existingCartItems.All(item => item.RestId ==foodItems.RestId);

                if (!sameRestaurant)
                {
                    TempData["Error"] = "You can only add items from the same restaurant to your cart. Please remove your current cart items before adding items from a new restaurant.";
                    return RedirectToAction("ViewCart", new { userId = temp }); 
                }
            }
            var existingCartItem = cartRepository.GetCartItemByfIdUid(foodItemId, temp);
          
          
            if (existingCartItem != null)
            {
               
                existingCartItem.Quantity++;
                cartRepository.Save();
            }
            else
            {
                var foodItem = foodItemRepository.GetFoodItemById(foodItemId);

                if (foodItem == null)
                {
                    ModelState.AddModelError("errorMessage", "Product not found.");
                    return RedirectToAction("AllRestaurant");
                }


                var addTocart = new Cart
                {
                    FoodId = foodItemId,
                    UserId = temp,
                    Quantity = 1,
                    Price = foodItem.Price,
                    RestId = foodItem.RestId,
                    destinationLatitude= restaurantRepository.GetRestaurantById(foodItem.RestId).Latitude,
                    destinationLongitude= restaurantRepository.GetRestaurantById(foodItem.RestId).Longitude

                };

                cartRepository.InsertCart(addTocart);
                cartRepository.Save();

            }
            TempData["Success"] = "Item Added to Cart successfully";

            return RedirectToAction("AllRestaurant");
        }
        public ActionResult ViewCart(int? userId)
        {
           
            if (userId == null)
            {
               
                return RedirectToAction("UserLogin", "Account");
            }
            
            var cartItems = cartRepository.GetCartItemsByUserId(userId);
      
            var carViewList = cartItems.Select(item => new Cart
            {
                CartId = item.CartId,
                UserId = item.UserId,
                Quantity = item.Quantity,
                Price = item.Price,
                FoodItem = foodItemRepository.GetFoodItemById(item.FoodId),
                FoodId=item.FoodId,
                RestId = item.RestId,
                Restaurant= restaurantRepository.GetRestaurantById(item.RestId),
                destinationLatitude = restaurantRepository.GetRestaurantById(item.RestId).Latitude,
                destinationLongitude = restaurantRepository.GetRestaurantById(item.RestId).Longitude

            });
           
            return View(carViewList);
        }

        [HttpPost]
        public ActionResult UpdateCartQuantity(int cartId, int newQuantity)
        {

            var cartItem = cartRepository.GetCartById(cartId);
            var foodItem = foodItemRepository.GetFoodItemById(cartItem.FoodId);
            if (!foodItem.Availability)
            {
                return Json(new { success = false, errorMessage = $" Item Not Available ." });
            }

            if (cartItem != null)
            {
                cartItem.Quantity = newQuantity;

                cartRepository.Save();
                var subtotal = cartItem.Quantity * cartItem.Price;
                return Json(new { success = true, subtotal });
            }
            return Json(new { success = true });
        }

        //RemoveCartItem
        [HttpPost]
        public ActionResult RemoveCartItem(int cartId)
        {
            int userid = Convert.ToInt32(Session["UserId"]);
           
            if (userid == 0)
            {
                TempData["ErrorMessage"] = "User not logged in.";
                return RedirectToAction("ViewCart", new { userId = userid });
            }

            var cartItem = cartRepository.GetCartItemByCartIdUid(cartId, userid);

            if (cartItem == null)
            {
                TempData["ErrorMessage"] = "Cart item not found.";
                return RedirectToAction("ViewCart", "User", new { userId = userid });
            }

            cartRepository.DeleteCart(cartItem.CartId);
            cartRepository.Save();
            return RedirectToAction("ViewCart", "User", new { userId = userid });
        }

        //orders
    
        public ActionResult PlaceOrder(int? userId)
        {

            if (userId == null)
            {
                var existingOrder = Session["OrderViewModel"] as OrderViewModel;
                return View(existingOrder);
            }
            else
            {
                var cartItems2 = cartRepository.GetCartItemsByUserId(userId);
                int[] cartIds1 = cartItems2.Select(item => item.CartId).ToArray();
                int custId = Convert.ToInt32(userId);
                var cartItems = cartRepository.GetCartItemById(cartIds1);
                var customer = userRepository.GetUserById(custId);

Food-Delivery-Website-master/FoodAppUILayer/Views/User/AllFoodItems.cshtml
@model IEnumerable<FoodAppDALLayer.Models.FoodItem>

@{
    ViewBag.Title = "AllFoodItems";
}

<div class="d-flex justify-content-end">
    <input type="text" id="searchInput" onkeyup="myFunction()" placeholder="Search for food.." style="padding: 5px; border-radius: 5px; border: 1px solid #ccc;">
</div>
<div class="container" id="myContainer">

    <div class="row mt-3" >
        @foreach (var item in Model)
        {
            <div class="col-lg-4 col-md-4 col-sm-6 mb-4">
                <div class="card h-100 shadow p-3  bg-body rounded">
                    <img src="data:image;base64,@item.Image" class="card-img-top" alt="..." style="height: 200px; object-fit: cover;">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title"><foodname>@Html.DisplayFor(modelItem => item.Name)</foodname></h5>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
                        <p class="mt-auto d-flex justify-content-between">
                            <span class="btn btn-success d-flex">Rs @Html.DisplayFor(modelItem => item.Price) /-</span>   <span class="text-secondary d-flex">@Html.DisplayFor(modelItem => item.Category.CategoryName)</span>
                        </p>

                        <span class="d-flex  justify-content-end">
                            @using (Html.BeginForm("AddToCart", "User", FormMethod.Post))
                            {
                                @Html.Hidden("foodItemId", item.FoodId)
                                <button type="submit" class="btn btn-warning d-flex"><i class="bi bi-cart"></i> Add to cart</button>
                            }
                        </span>

                    </div>
                </div>
            </div>
        }
    </div>
</div>


<script>
    function myFunction() {
        var input, filter, container, foodname, i, txtValue;
        input = document.getElementById('searchInput');
        filter = input.value.toUpperCase();
        container = document.getElementById("myContainer");
        foodname = container.getElementsByTagName('foodname');
        for (i = 0; i < foodname.length; i++) {
            txtValue = foodname[i].textContent || foodname[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                foodname[i].closest('.col-lg-4').style.display = ""; 
            } else {
                foodname[i].closest('.col-lg-4').style.display = "none"; 
            }
        }
    }
</script>

Food-Delivery-Website-master/FoodAppUILayer/Views/User/AllRestaurant.cshtml
@model IEnumerable<FoodAppDALLayer.Models.Restaurant>

@{
    ViewBag.Title = "AllRestaurant";

}


<P class="text-center shadow-lg bg-success text-white rounded">@TempData["Success"]</P>

<div class="container">
 
    <div class="row mt-3" id="myContainer">
        @foreach (var order in ViewBag.Top5Orders)
        {
            <div class="col-lg-3 col-md-3 col-sm-6 mb-4">
                <div class="card h-100 shadow p-3  bg-body rounded">
                    <img src="data:image;base64,@order.FoodItem.Image" class="card-img-top" alt="..." style="height: 200px; object-fit: cover;">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">@order.FoodItem.Name  <br /><span style="color: #555; font-size: 16px;"><i class="bi bi-geo-alt-fill"></i> @order.FoodItem.Restaurant.City</span> </h5>
                        <p class="mt-auto d-flex justify-content-between"> <span class="rounded-2 text-danger p-2"><i class="bi bi-tag-fill"></i>Popular </span>
                            <span class="btn btn-success d-flex">Rs @order.FoodItem.Price /-</span> <span class="d-flex  justify-content-end">
                                @using (Html.BeginForm("AddToCart", "User", FormMethod.Post))
                                {
                                    <input type="hidden" name="foodItemId" value="@order.FoodItem.FoodId" />

                                    <button type="submit" class="btn btn-warning d-flex"><i class="bi bi-cart"></i> Add to cart</button>
                                }
                            </span>
                        </p>
                       

                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div class="text-center">
    <h2 class="mb-4 text-uppercase fst-italic mt-3">Best Restaurants</h2>
</div>
<div class="d-flex justify-content-end">
    <input type="text" id="searchInput" onkeyup="myFunction()" placeholder="Search for cities.." style="padding: 5px; border-radius: 5px; border: 1px solid #ccc;">
</div>

<div class="container" id="restaurantContainer">

    @foreach (var item in Model)
    {<div class="row" style="margin: 20px; border: 1px solid #ddd; padding: 10px; border-radius: 5px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); transition: 0.3s; background-image: url('data:image;base64,@item.Image'); background-size: cover;">
            <div class="col-3" style="text-align: center;">
                <img src="data:image;base64,@item.Image" alt="Image" width="100" height="100" style="border-radius: 50%; border: 2px solid #ddd; transition: transform .2s;" />
            </div>
            <div class="col-7" style="background-color: rgba(255, 255, 255, 0.8); padding: 10px; border-radius: 5px;">
                <h1 style="color: #333; font-size: 24px; font-weight: bold;">@Html.DisplayFor(modelItem => item.Name)  <span style="color: #555; font-size: 16px;"><i class="bi bi-geo-alt-fill"></i> @Html.DisplayFor(modelItem => item.City)</span></h1>
                <p style="color: #777; font-size: 18px; font-style: italic;">@Html.DisplayFor(modelItem => item.Address)</p>
                <city style="visibility:hidden">@Html.DisplayFor(modelItem => item.City)</city>
            </div>
            <div class="col-2" style="text-align: center; display: flex; align-items: center; justify-content: center; flex-direction: column;">

                <a href="@Url.Action("AllFoodItems", "User", new { id = item.RestId })" class="btn-warning" style="color:white !important; padding: 10px 20px; text-decoration: none; border-radius: 5px; transition: background-color .3s;">
                    <span style="font-size: 18px; font-weight: bold;">Menu</span>  <i class="bi bi-arrow-right-circle"></i>
                </a>
            </div>
        </div>
    }

</div>

<script>
    function myFunction() {
        var input, filter, container, cities, i, txtValue;
        input = document.getElementById('searchInput');
        filter = input.value.toUpperCase();
        container = document.getElementById("restaurantContainer");
        cities = container.getElementsByTagName('city');
        for (i = 0; i < cities.length; i++) {
            txtValue = cities[i].textContent || cities[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                cities[i].closest('.row').style.display = ""; 
            } else {
                cities[i].closest('.row').style.display = "none"; 
            }
        }
    }
</script>

Food-Delivery-Website-master/FoodAppUILayer/Views/User/EditUser.cshtml
@model FoodAppDALLayer.Models.User

@{
    ViewBag.Title = "EditUser";
}



@using (Html.BeginForm("EditUser", "User", FormMethod.Post, new { @class = "col-md-6" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Welcome @Model.FirstName @Model.LastName</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UserId)
    @Html.HiddenFor(model => model.Password)
    @Html.HiddenFor(model => model.RoleId)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group mt-3">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-info" />
        </div>
    </div>
</div>
}

Food-Delivery-Website-master/FoodAppUILayer/Views/User/OrderByUser.cshtml
@model IEnumerable<FoodAppDALLayer.Models.Order>
@{
    ViewBag.Title = "OrderByUser";
}

<h3 style="color:darkblue">My Orders</h3>
<P class="text-center shadow-lg bg-warning text-white rounded">@TempData["DeleteMsg"]</P>
<div class="container" id="myContainer">

    @foreach (var item in Model)
    {<div class="row" style="margin: 20px; border: 1px solid #ddd; padding: 10px; border-radius: 5px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); transition: 0.3s;">
           <div class="col-3" style="text-align: center; overflow: hidden;">
               <img src="data:image;base64,@item.FoodItem.Image" alt="Image" style="width: 100%; height: 100%; object-fit: cover; border-radius: 10%; border: 2px solid #ddd; transition: transform .2s;" />
           </div>
            <div class="col-7" style="background-color: rgba(255, 255, 255, 0.8); padding: 10px; border-radius: 5px;">

                <h1 style="color: #333; font-size: 24px; font-weight: bold;">Order Id: @Html.DisplayFor(modelItem => item.OrderId) </h1>
                @foreach (var food in @item.OrderItems.ToList())
                {
                   <p  style="color: #777; font-size: 18px; font-style: italic;"> @Html.DisplayFor(modelItem => food.FoodItem.Name) :  @Html.DisplayFor(modelItem => food.Quantity)</p>
                }
                <p style="color: #777; font-size: 18px; font-style: italic;">Address : @Html.DisplayFor(modelItem => item.DeliveryAddress), </p>
                <p style="color: #777; font-size: 18px; font-style: italic;">Ordered Date : @Html.DisplayFor(modelItem => item.DateOfOrder) </p>
                <p style="color: #777; font-size: 18px; font-style: italic;">Rs @Html.DisplayFor(modelItem => item.TotalAmount) /-</p>


            </div>
            <div class="col-2" style="text-align: center; display: flex; align-items: center; justify-content: center; flex-direction: column;">
                @if (item.OrderStatus == "Preparing Order")
                {
                    <a href="@Url.Action("DeleteOrder", "User", new { id = item.OrderId })" class="btn-warning" style="color:white !important; padding: 10px 20px; text-decoration: none; border-radius: 5px; transition: background-color .3s;">
                        <span style="font-size: 18px; font-weight: bold;">Cancel Order</span>  <i class="bi bi-arrow-right-circle"></i>
                    </a>
                }
                else
                {
                    <span class="bg-light text-success rounded">@item.OrderStatus</span>
                }
            </div>
        </div>
    }

</div>

Food-Delivery-Website-master/FoodAppUILayer/Views/User/OrderConfirmation.cshtml
@model IEnumerable<FoodAppDALLayer.Models.Order>

@{
    ViewBag.Title = "OrderConfirmation";
}
<style>
    .card {
        border: none;
        box-shadow: 0 0 10px rgba(0,0,0,0.15);
        border-radius: 15px;
        overflow: hidden;
        margin-bottom: 20px;
    }

    .card-body {
        padding: 20px;
    }

    .card-logo {
        width: 100px;
        height: 100px;
        margin: 20px auto;
        display: block;
    }

    .card-title {
        color: #007BFF;
        font-weight: bold;
        margin-top: 20px;
    }

    .card-text {
        color: #6c757d;
        margin-bottom: 20px;
    }

    .btn-primary {
        background-color: #007BFF;
        border: none;
        color: white;
    }


    .card-text table {
        width: 100%;
    }

        .card-text table td:first-child {
            width: 30%;
            font-weight: bold;
        }
</style>

<div class="container mt-5">
    <h2 class="text-center text-primary">Order Confirmation</h2>
    @foreach (var item in Model)
    {
        <div class="card mt-3">
            <div class="card-body">
                <!-- Removed text-center class -->
                <div class="card-logo">
                    <img src="~/Images/success.png" width="100" height="100" />
                </div>
                <h5 class="card-title">Order Id: @Html.DisplayFor(modelItem => item.OrderId)</h5>
                <h6 class="card-subtitle mb-2 text-muted">Order Date: @Html.DisplayFor(modelItem => item.DateOfOrder)</h6>
                <div class="card-text">
                    <table>
                        <tr>
                            <td>Qyt:</td>
                            <td>@Html.DisplayFor(modelItem => item.Qty)</td>
                        </tr>
                        <tr>
                            <td>Discount:</td>
                            <td>@Html.DisplayFor(modelItem => item.Discount) %</td>
                        </tr>
                        <tr>
                            <td>Total Amount</td>
                            <td>@Html.DisplayFor(modelItem => item.TotalAmount) </td>
                        </tr>
                        <tr>
                            <td>Delivery Address:</td>
                            <td>@Html.DisplayFor(modelItem => item.DeliveryAddress)</td>
                        </tr>
                        <tr>
                            <td>Payment Type:</td>
                            <td>@Html.DisplayFor(modelItem => item.PaymentType)</td>
                        </tr>
                        <tr>
                            <td>Estimated Delivery Time:</td>
                            <td>@Html.DisplayFor(modelItem => item.EstimatedDeliveryTime)</td>
                        </tr>
                    </table>
                </div>
                <a href="@Url.Action("AllRestaurant")" class="btn btn-info">Continue Order</a>
                <a href="@Url.Action("AddRatings" , "Rating", new {id=item.OrderId})" class="btn btn-info">Give Your Rating here</a>
            </div>
        </div>
    }
</div>